version: 2.1

jobs:
  build:
    docker:
      - image: jdrouet/docker-with-buildx:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.8
      - run:
          command: |
            docker version
            docker buildx version
