version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          command: |
            docker version
            docker buildx version

workflows:
  docker-release:
    jobs:
      - build:
          filters:
            branches:
              only:
                - circleci-test
